name: currency_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cool_dropdown: ^1.4.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.4
  google_fonts: ^3.0.1
  http: ^0.13.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/image/
