// ignore_for_file: non_constant_identifier_names

class CurrencyData {
  final dynamic AUD,
      BGN,
      BRL,
      CAD,
      CHF,
      CNY,
      CZK,
      DKK,
      EUR,
      GBP,
      HKD,
      HRK,
      HUF,
      IDR,
      ILS,
      INR,
      ISK,
      JPY,
      KRW,
      MXN,
      MYR,
      NOK,
      NZD,
      PHP,
      PLN,
      RON,
      SEK,
      SGD,
      THB,
      TRY,
      ZAR;

  CurrencyData({
    required this.AUD,
    required this.BGN,
    required this.BRL,
    required this.CAD,
    required this.CHF,
    required this.CNY,
    required this.CZK,
    required this.DKK,
    required this.EUR,
    required this.GBP,
    required this.HKD,
    required this.HRK,
    required this.HUF,
    required this.IDR,
    required this.ILS,
    required this.INR,
    required this.ISK,
    required this.JPY,
    required this.KRW,
    required this.MXN,
    required this.MYR,
    required this.NOK,
    required this.NZD,
    required this.PHP,
    required this.PLN,
    required this.RON,
    required this.SEK,
    required this.SGD,
    required this.THB,
    required this.TRY,
    required this.ZAR,
  });

  factory CurrencyData.fromJson(Map<String, dynamic> json) => CurrencyData(
        AUD: json["AUD"],
        BGN: json["BGN"],
        BRL: json["BRL"],
        CAD: json["CAD"],
        CHF: json["CHF"],
        CNY: json["CNY"],
        CZK: json["CZK"],
        DKK: json["DKK"],
        EUR: json["EUR"],
        GBP: json["GBP"],
        HKD: json["HKD"],
        HRK: json["HRK"],
        HUF: json["HUF"],
        IDR: json["IDR"],
        ILS: json["ILS"],
        INR: json["INR"],
        ISK: json["ISK"],
        JPY: json["JPY"],
        KRW: json["KRW"],
        MXN: json["MXN"],
        MYR: json["MYR"],
        NOK: json["NOK"],
        NZD: json["NZD"],
        PHP: json["PHP"],
        PLN: json["PLN"],
        RON: json["RON"],
        SEK: json["SEK"],
        SGD: json["SGD"],
        THB: json["THB"],
        TRY: json["TRY"],
        ZAR: json["ZAR"],
      );
}

class Currency {
  final String title;
  final String symbol;

  Currency({
    required this.title,
    required this.symbol,
  });
}

Map<String, String> currencies = {
  "AUD": "Australian Dollar",
  "BGN": "Bulgarian Lev",
  "BRL": "Brazilian Real",
  "CAD": "Canadian Dollar",
  "CHF": "Swiss Franc",
  "CNY": "Chinese Renminbi Yuan",
  "CZK": "Czech Koruna",
  "DKK": "Danish Krone",
  "EUR": "Euro",
  "GBP": "British Pound",
  "HKD": "Hong Kong Dollar",
  "HRK": "Croatian Kuna",
  "HUF": "Hungarian Forint",
  "IDR": "Indonesian Rupiah",
  "ILS": "Israeli New Sheqel",
  "INR": "Indian Rupee",
  "ISK": "Icelandic Króna",
  "JPY": "Japanese Yen",
  "KRW": "South Korean Won",
  "MXN": "Mexican Peso",
  "MYR": "Malaysian Ringgit",
  "NOK": "Norwegian Krone",
  "NZD": "New Zealand Dollar",
  "PHP": "Philippine Peso",
  "PLN": "Polish Złoty",
  "RON": "Romanian Leu",
  "SEK": "Swedish Krona",
  "SGD": "Singapore Dollar",
  "THB": "Thai Baht",
  "TRY": "Turkish Lira",
  "USD": "United States Dollar",
  "ZAR": "South African Rand",
};
